[ejs.landing]
updateAvailableTooltip = "Atualizacao disponivel"
usernamePlaceholder = "Usuario"
usernameEditButton = "Editar"
settingsTooltip = "Configuracoes"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "STATUS DA MOJANG"
mojangStatusTooltipTitle = "Servicos"
mojangStatusNETitle = "Nao essenciais"
newsButton = "NOTICIAS"
launchButton = "JOGAR"
launchButtonPlaceholder = "&#8226; Nenhum servidor selecionado"
launchDetails = "Aguarde..."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Buscando noticias..."
newsErrorFailedSpan = "Falha ao carregar noticias"
newsErrorRetryButton = "Tentar novamente"
newsErrorNoneSpan = "Sem noticias"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "LOGIN DO MINECRAFT"
loginEmailError = "* Valor invalido"
loginEmailPlaceholder = "E-MAIL OU USUARIO"
loginPasswordError = "* Obrigatorio"
loginPasswordPlaceholder = "SENHA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "esqueceu a senha?"
loginRememberMeText = "lembrar de mim?"
loginButtonText = "ENTRAR"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Precisa de uma conta?"
loginPasswordDisclaimer1 = "Sua senha e enviada diretamente para a Mojang e nunca e armazenada."
loginPasswordDisclaimer2 = "{appName} nao e afiliado a Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Opcoes de Login"
loginWithMicrosoft = "Entrar com Microsoft"
loginWithMojang = "Entrar com Mojang"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores Disponiveis"
serverSelectConfirm = "Selecionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Selecionar uma Conta"
accountSelectConfirm = "Selecionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configuracoes"
navAccount = "Conta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Sobre"
navUpdates = "Atualizacoes"
navDone = "Concluir"
tabAccountHeaderText = "Configuracoes da Conta"
tabAccountHeaderDesc = "Adicione novas contas ou gerencie as existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Adicionar Conta Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Adicionar Conta Mojang"
minecraftTabHeaderText = "Configuracoes do Minecraft"
minecraftTabHeaderDesc = "Opcoes relacionadas ao inicio do jogo."
gameResolutionTitle = "Resolucao do Jogo"
launchFullscreenTitle = "Iniciar em tela cheia."
autoConnectTitle = "Conectar automaticamente ao servidor ao iniciar."
launchDetachedTitle = "Iniciar o processo do jogo separado do launcher."
launchDetachedDesc = "Se o jogo nao estiver separado, fechar o launcher tambem fechara o jogo."
tabModsHeaderText = "Configuracoes de Mods"
tabModsHeaderDesc = "Ative ou desative mods."
switchServerButton = "Trocar"
requiredMods = "Mods Obrigatorios"
optionalMods = "Mods Opcionais"
dropinMods = "Mods Adicionados"
addMods = "Adicionar Mods"
dropinRefreshNote = "(F5 para atualizar)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Ative ou desative shaders. Shaders so rodam bem em computadores mais potentes. Voce pode adicionar pacotes personalizados aqui."
selectShaderpack = "Selecionar Shaderpack"
tabJavaHeaderText = "Configuracoes do Java"
tabJavaHeaderDesc = "Gerencie a configuracao do Java (avancado)."
memoryTitle = "Memoria"
maxRAM = "RAM Maxima"
minRAM = "RAM Minima"
memoryDesc = "A RAM minima recomendada e 3 gigabytes. Definir o minimo e o maximo com o mesmo valor pode reduzir travamentos."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponivel"
javaExecutableTitle = "Executavel do Java"
javaExecSelDialogTitle = "Selecionar Executavel do Java"
javaExecSelButtonText = "Escolher Arquivo"
javaExecDesc = "O executavel do Java e validado antes de iniciar o jogo."
javaPathDesc = "O caminho deve terminar com <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opcoes adicionais da JVM"
jvmOptsDesc = "Opcoes fornecidas a JVM durante a execucao. <em>-Xms</em> e <em>-Xmx</em> nao devem ser incluidos."
launcherTabHeaderText = "Configuracoes do Launcher"
launcherTabHeaderDesc = "Opcoes relacionadas ao proprio launcher."
allowPrereleaseTitle = "Permitir atualizacoes pre-release."
allowPrereleaseDesc = "Pre-releases incluem recursos novos que talvez ainda nao tenham sido totalmente testados ou integrados.<br>Isto sempre ficara ativo se voce estiver usando uma versao pre-release."
dataDirectoryTitle = "Diretorio de Dados"
selectDataDirectory = "Selecionar Diretorio de Dados"
chooseFolder = "Escolher Pasta"
dataDirectoryDesc = "Todos os arquivos do jogo e instalacoes locais do Java serao armazenados no diretorio de dados.<br>Capturas de tela e mundos salvos ficam na pasta da instancia da configuracao correspondente do servidor."
aboutTabHeaderText = "Sobre"
aboutTabHeaderDesc = "Veja informacoes e notas da versao atual."
aboutTitle = "{appName}"
stableRelease = "Versao Estavel"
versionText = "Versao "
sourceGithub = "Codigo-fonte (GitHub)"
support = "Suporte"
devToolsConsole = "Console DevTools"
releaseNotes = "Notas da Versao"
changelog = "Registro de Alteracoes"
noReleaseNotes = "Sem notas da versao"
viewReleaseNotes = "Ver notas da versao no GitHub"
launcherUpdatesHeaderText = "Atualizacoes do Launcher"
launcherUpdatesHeaderDesc = "Baixe, instale e veja atualizacoes do launcher."
checkForUpdates = "Verificar Atualizacoes"
whatsNew = "Novidades"
updateReleaseNotes = "Notas da Atualizacao"

[ejs.waiting]
waitingText = "Aguardando a Microsoft..."

[ejs.welcome]
continueButton = "CONTINUAR"

[js.discord]
waiting = "Aguardando cliente..."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Login Microsoft"
microsoftLogoutTitle = "Logout Microsoft"

[js.login]
login = "ENTRAR"
loggingIn = "ENTRANDO"
success = "SUCESSO"
tryAgain = "Tentar Novamente"

[js.login.error]
invalidValue = "* Valor invalido"
requiredValue = "* Obrigatorio"

[js.login.error.unknown]
title = "Erro desconhecido durante o login"
desc = "Ocorreu um erro desconhecido. Veja o console para mais detalhes."

[js.landing.launch]
pleaseWait = "Aguarde..."
failureTitle = "Erro ao iniciar"
failureText = "Veja o console (CTRL + Shift + i) para mais detalhes."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Nenhuma conta selecionada"

[js.landing.selectedServer]
noSelection = "Nenhum servidor selecionado"
loading = "Carregando..."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "OFFLINE"
players = "JOGADORES"

[js.landing.systemScan]
checking = "Verificando informacoes do sistema..."
noCompatibleJava = "Nenhuma instalacao<br>compativel do Java encontrada"
installJavaMessage = "Para iniciar o Minecraft, voce precisa de uma instalacao 64-bit do Java {major}. Deseja que o launcher instale uma copia?"
installJava = "Instalar Java"
installJavaManually = "Instalar Manualmente"
javaDownloadPrepare = "Preparando download do Java..."
javaDownloadFailureTitle = "Erro ao baixar o Java"
javaDownloadFailureText = "Veja o console (CTRL + Shift + i) para mais detalhes."
javaRequired = "Java e necessario<br>para iniciar"
javaRequiredMessage = "Uma instalacao x64 valida do Java {major} e necessaria para iniciar.<br><br>Instale o Java manualmente ou deixe o launcher baixar uma copia compativel."
javaRequiredDismiss = "Entendi"
javaRequiredCancel = "Voltar"

[js.landing.downloadJava]
findJdkFailure = "Falha ao encontrar uma distribuicao OpenJDK."
javaDownloadCorruptedError = "O JDK baixado tem hash invalido; o arquivo pode estar corrompido."
extractingJava = "Extraindo Java"
javaInstalled = "Java instalado!"

[js.landing.dlAsync]
loadingServerInfo = "Carregando informacoes do servidor..."
fatalError = "Erro Fatal"
unableToLoadDistributionIndex = "Nao foi possivel carregar uma copia do indice de distribuicao. Veja o console (CTRL + Shift + i) para mais detalhes."
pleaseWait = "Aguarde..."
errorDuringLaunchTitle = "Erro ao iniciar"
seeConsoleForDetails = "Veja o console (CTRL + Shift + i) para mais detalhes."
validatingFileIntegrity = "Validando integridade dos arquivos..."
errorDuringFileVerificationTitle = "Erro ao verificar arquivos"
downloadingFiles = "Baixando arquivos..."
errorDuringFileDownloadTitle = "Erro ao baixar arquivos"
preparingToLaunch = "Preparando para iniciar..."
launchingGame = "Iniciando jogo..."
launchWrapperNotDownloaded = "O arquivo principal, LaunchWrapper, nao foi baixado corretamente. Por isso, o jogo nao pode iniciar.<br><br>Para corrigir, verifique sua conexao, antivirus e tente iniciar novamente."
doneEnjoyServer = "Pronto. Bom jogo!"
checkConsoleForDetails = "Verifique o console (CTRL + Shift + i) para mais detalhes."

[js.landing.news]
checking = "Buscando noticias"

[js.landing.discord]
loading = "Carregando jogo..."
joining = "Entrando no servidor!"
joined = "Explorando o servidor!"

[js.overlay]
dismiss = "Fechar"

[js.settings.fileSelectors]
executables = "Executaveis"
allFiles = "Todos os Arquivos"

[js.settings.mstfLogin]
errorTitle = "Algo deu errado"
errorMessage = "A autenticacao Microsoft falhou. Tente novamente."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Algo deu errado"
errorMessage = "O logout da Microsoft falhou. Tente novamente."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Selecionar Conta"
selectedButton = "Conta Selecionada &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Aviso<br>Esta e sua ultima conta"
lastAccountWarningMessage = "Para usar o launcher, voce precisa estar logado em pelo menos uma conta. Sera necessario entrar novamente depois.<br><br>Tem certeza de que deseja sair?"
confirmButton = "Tenho certeza"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Usuario"
uuid = "UUID"
selectAccount = "Selecionar Conta"
selectedAccount = "Conta Selecionada &#10004;"
logout = "Sair"

[js.settings.dropinMods]
removeButton = "Remover"
deleteFailedTitle = "Falha ao excluir<br>Mod adicionado {fullName}"
deleteFailedMessage = "Verifique se o arquivo nao esta em uso e tente novamente."
failedToggleTitle = "Falha ao alternar<br>um ou mais mods adicionados"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Servidor Principal"

[js.settings.java]
selectedJava = "Selecionado: Java {version} ({vendor})"
invalidSelection = "Selecao invalida"
requiresJava = "Requer Java {major} x64."
availableOptions = "Opcoes disponiveis para Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Versao Estavel"
releaseNotesFailed = "Falha ao carregar notas da versao."

[js.settings.updates]
newReleaseTitle = "Nova versao disponivel"
newPreReleaseTitle = "Nova pre-release disponivel"
downloadingButton = "Baixando..."
downloadButton = "Baixar pelo GitHub<span style=\"font-size: 10px;color: gray;text-shadow: none !important;\">Feche o launcher e execute o dmg para atualizar.</span>"
latestVersionTitle = "Voce esta usando a versao mais recente"
checkForUpdatesButton = "Verificar Atualizacoes"
checkingForUpdatesButton = "Verificando Atualizacoes..."

[js.settings.msftLogin]
errorTitle = "Falha no Login Microsoft"
errorMessage = "Nao foi possivel autenticar sua conta Microsoft. Tente novamente."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erro Fatal: Nao foi possivel carregar o indice de distribuicao"
fatalErrorMessage = "Nao foi possivel conectar aos servidores para baixar o indice de distribuicao. Nenhuma copia local estava disponivel. <br><br>O indice de distribuicao e um arquivo essencial que fornece as informacoes mais recentes do servidor. O launcher nao consegue iniciar sem ele. Verifique sua conexao com a internet e abra o aplicativo novamente."
closeButton = "Fechar"

[js.uibinder.validateAccount]
failedMessageTitle = "Falha ao atualizar login"
failedMessage = "Nao foi possivel atualizar o login de <strong>{account}</strong>. Selecione outra conta ou entre novamente."
failedMessageSelectAnotherAccount = "Nao foi possivel atualizar o login de <strong>{account}</strong>. Entre novamente."
loginButton = "Entrar"
selectAnotherAccountButton = "Selecionar outra conta"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Verificando atualizacoes..."
installNowButton = "Instalar agora"
checkForUpdatesButton = "Verificar atualizacoes"

[js.auth.microsoft.error]
noProfileTitle = "Erro durante o login:<br>Perfil nao configurado"
noProfileDesc = "Sua conta Microsoft ainda nao tem um perfil do Minecraft configurado. Se voce comprou o jogo recentemente ou resgatou pelo Xbox Game Pass, configure seu perfil em <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Se ainda nao comprou o jogo, voce tambem pode comprar em <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erro durante o login:<br>Sem conta Xbox"
noXboxAccountDesc = "Sua conta Microsoft nao tem uma conta Xbox associada."
xblBannedTitle = "Erro durante o login:<br>Xbox Live indisponivel"
xblBannedDesc = "Sua conta Microsoft e de um pais onde o Xbox Live nao esta disponivel ou foi bloqueado."
under18Title = "Erro durante o login:<br>Aprovacao dos pais necessaria"
under18Desc = "Contas de usuarios menores de 18 anos devem ser adicionadas a uma Familia por um adulto."
unknownTitle = "Erro desconhecido durante o login"
unknownDesc = "Ocorreu um erro desconhecido. Veja o console para mais detalhes."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erro interno:<br>Metodo nao permitido"
methodNotAllowedDesc = "Metodo nao permitido. Informe este erro."
notFoundTitle = "Erro interno:<br>Nao encontrado"
notFoundDesc = "O endpoint de autenticacao nao foi encontrado. Informe este problema."
accountMigratedTitle = "Erro durante o login:<br>Conta migrada"
accountMigratedDesc = "Voce tentou entrar com uma conta migrada. Tente novamente usando o e-mail da conta como usuario."
invalidCredentialsTitle = "Erro durante o login:<br>Credenciais invalidas"
invalidCredentialsDesc = "O e-mail ou senha informado esta incorreto. Tente novamente."
tooManyAttemptsTitle = "Erro durante o login:<br>Muitas tentativas"
tooManyAttemptsDesc = "Houve muitas tentativas de login com esta conta recentemente. Tente novamente mais tarde."
invalidTokenTitle = "Erro durante o login:<br>Token invalido"
invalidTokenDesc = "O token de acesso fornecido e invalido."
tokenHasProfileTitle = "Erro durante o login:<br>Token ja tem perfil"
tokenHasProfileDesc = "O token de acesso ja tem um perfil atribuido. A selecao de perfis ainda nao esta implementada."
credentialsMissingTitle = "Erro durante o login:<br>Credenciais ausentes"
credentialsMissingDesc = "Usuario/senha nao foram enviados ou a senha tem menos de 3 caracteres."
invalidSaltVersionTitle = "Erro durante o login:<br>Versao de salt invalida"
invalidSaltVersionDesc = "Versao de salt invalida."
unsupportedMediaTypeTitle = "Erro interno:<br>Tipo de midia nao suportado"
unsupportedMediaTypeDesc = "Tipo de midia nao suportado. Informe este erro."
accountGoneTitle = "Erro durante o login:<br>Conta migrada"
accountGoneDesc = "A conta foi migrada para uma conta Microsoft. Entre com Microsoft."
unreachableTitle = "Erro durante o login:<br>Indisponivel"
unreachableDesc = "Nao foi possivel acessar os servidores de autenticacao. Verifique se estao online e se voce esta conectado a internet."
gameNotPurchasedTitle = "Erro durante o login:<br>Jogo nao comprado"
gameNotPurchasedDesc = "A conta que voce esta tentando usar nao comprou uma copia do Minecraft. Voce pode comprar em <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erro desconhecido durante o login"
unknownErrorDesc = "Ocorreu um erro desconhecido. Veja o console para mais detalhes."
